version: '3.9'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10

  user-service:
    build: ./user-service
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    
  account-service:
    build: ./account-service
    ports:
      - "8083:8083"
    depends_on:
      db:
        condition: service_healthy

