server:
  port: 8085

spring:
  application:
    name: api-gateway
  cloud:
    config:
      profile: dev
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: http://user-service:8080
          predicates:
            - Path=/api/users/**
        - id: accounts-service
          uri: http://account-service:8083
          predicates:
            - Path=/api/accounts/**

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/